### ISSUE TITLE
Upravy css

### ISSUE THREAD

**Issue by mirelon** [TIS2016/VernostneProgramy#7]
Na to, aby sa dali pouzit css subory, napr. https://github.com/TIS2016/VernostneProgramy/blob/doc/src/collapsable.css
nemozu sa ovplyvnovat globalne veci ako body, div, ... Vsetko by malo byt scopovane na ten element, v ktorom sa odohrava vizualizacia.

A treba to asi trochu upratat, lebo su tam konflikty aj s druhym css https://github.com/TIS2016/VernostneProgramy/blob/doc/src/Treant.css

**Comment by ivan-lattak** [comment]
Na zobrazovanie tooltipov k vrcholom vytvárame `div`-y, ktorých parent je `body`. Je toto to, na čo poukazuješ?

**Comment by mirelon** [comment]
Nie, poukazujem na to, ze ked chcem tu vizualizaciu pouzit, potrebujem mat nekonfliktne css.

Konflikt je napriklad v buttone, ktorym sa to rozbaluje (.collapse-switch) - v jednom subore ma velkost 3x3 pixely, v druhom ma 100% velkost.

Uz som si to upravil, aby to nejak fungovalo, dal som to do jedneho css:

```
.chart { height: 100%; margin: 5px; width: 100%; }
.Treant > .node { padding: 3px; border: 1px solid #484848; border-radius: 3px; }
.Treant > .node img { width: 100%; height: 100%; }

.Treant .collapse-switch { width: 100%; height: 100%; border: none; }
.Treant .node.collapsed { background-color: #DEF82D; }

.Treant { position: relative; overflow: hidden; padding: 0 !important; }
.Treant > .node,
.Treant > .pseudo { position: absolute; display: block; visibility: hidden; }
.Treant.Treant-loaded .node,
.Treant.Treant-loaded .pseudo { visibility: visible; }
.Treant > .pseudo { width: 0; height: 0; border: none; padding: 0; }
.Treant .collapse-switch { display: block; position: absolute; top: 0px; right: 0px; cursor: pointer; }
.Treant .collapsed .collapse-switch { background-color: #868DEE; }
.Treant > .node img {	border: none; float: left; }.Treant .node.collapsed .collapse-switch { background: none; }
```

Idealne by bolo, aby ste aj vy tu v gite mali to, co potom ja pouzijem (neviem, ci som toto css spravil tak, ako ste zamyslali)

**Comment by ivan-lattak** [comment]
Neuvedomovali sme si, že takéto konflikty existujú. Ten css súbor, o ktorom hovoríš, je neupravovaný z knižnice, a my sme s týmto problémy nemali.

**Comment by mirelon** [comment]
Ok, mohli by ste to teda dat do jedneho suboru, aby som s tym ani ja nemal problemy.

Aby ste chapali, preco to mne funguje inak. Pri css pri konfliktoch zavisi na poradi importov. Vy ich mate definovane v nejakom poradi v index.html. V railsoch sa assety autoloaduju, a zrovna tu to bolo v opacnom poradi, preto vrcholy stromu neboli klikatelne.

Best practice je nemat konflikty.

**Comment by ivan-lattak** [comment]
Ktorý z tých css súborov si ponechal, do ktorého to mám dať?

**Comment by mirelon** [comment]
to je jedno, ja som si len skopiroval obsah oboch a dal to zvlast...

**Comment by ivan-lattak** [comment]
Closed by d22e2729eb939f47aa660844482329bdd9714229
